### ISSUE TITLE
Exception in Windows build

### ISSUE THREAD

**Issue by radioegor146** [ezhevita/YandexKeyExtractor#41]
Latest windows build (V1.1 to be precise) throws this error when ran:
```
Unhandled exception. System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.DeserializeAsync[TValue](Stream , JsonSerializerOptions , CancellationToken )
   at System.Net.Http.Json.HttpClientJsonExtensions.<>c__9`1.<FromJsonAsyncCore>b__9_0(Stream stream, JsonSerializerOptions options, CancellationToken cancellation)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient, Task`1, Boolean, CancellationTokenSource, Func`4, TJsonOptions, CancellationToken)
   at YandexKeyExtractor.WebHandler.TryGetCountry()
   at Program.<<Main>$>g__RetrieveBackup|0_0(WebHandler)
   at Program.<Main>$(String[])
   at Program.<Main>(String[])
```

**Comment by ezhevita** [comment]
Hi, thanks for the report! I'll see what I can do

**Comment by ezhevita** [comment]
Can you please try the latest CI build? You can download it from here: https://github.com/ezhevita/YandexKeyExtractor/actions/runs/11487076552

**Comment by radioegor146** [comment]
Yep, works flawlessly!
